# Generated by Django 4.1.1 on 2022-09-25 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('crm', models.CharField(blank=True, max_length=10, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consultas.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('laudo', models.CharField(blank=True, max_length=1000, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consultas.medico')),
                ('procedimento', models.ManyToManyField(blank=True, to='consultas.procedimento')),
            ],
        ),
    ]
