# Generated by Django 4.1.1 on 2022-09-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_procedimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='codigo',
            field=models.PositiveIntegerField(),
        ),
    ]
